import { ProductInterface } from '../Interfaces/product.interface';

export class ProductService {
  productsArray: ProductInterface[] = [
    {
      id: '1',
      name: 'Beli Čaj',
      picture: '../assets/white-tea.png',
      price: 500,
      text: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sunt nostrum quia labore facilis corporis illum voluptatum cupiditate eos neque temporibus!',
      desc: '## Beli Čaj\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris.  Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl. \n### Za Šta Je Dobar\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl .Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl.\n### Koliko Često Piti\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl .Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt.\n### Odakle Ga Nabavljamo\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis.',
    },
    {
      id: '2',
      name: 'Crni Čaj',
      picture: '../assets/black-tea.png',
      price: 500,
      text: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sunt nostrum quia labore facilis corporis illum voluptatum cupiditate eos neque temporibus!',
      desc: '## Crni Čaj\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl. \n### Za Šta Je Dobar\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl .Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl.\n### Koliko Često Piti\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl .Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt.\n### Odakle Ga Nabavljamo\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis.',
    },
    {
      id: '3',
      name: 'Zeleni Čaj',
      picture: '../assets/green-tea.png',
      price: 500,
      text: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sunt nostrum quia labore facilis corporis illum voluptatum cupiditate eos neque temporibus!',
      desc: '## Zeleni Čaj\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl. \n### Za Šta Je Dobar\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl .Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl.\n### Koliko Često Piti\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl .Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt.\n### Odakle Ga Nabavljamo\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis.',
    },
    {
      id: '4',
      name: 'Čaj od Đumbira',
      picture: '../assets/ginger-tea.png',
      price: 500,
      text: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sunt nostrum quia labore facilis corporis illum voluptatum cupiditate eos neque temporibus!',
      desc: '## Čaj od Đumbira\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl. \n### Za Šta Je Dobar\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl .Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl.\n### Koliko Često Piti\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl .Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt.\n### Odakle Ga Nabavljamo\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis.',
    },
    {
      id: '5',
      name: 'Čaj od Mente',
      picture: '../assets/peppermint-tea.png',
      price: 500,
      text: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sunt nostrum quia labore facilis corporis illum voluptatum cupiditate eos neque temporibus!',
      desc: '## Čaj od Mente\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl. \n### Za Šta Je Dobar\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl .Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl.\n### Koliko Često Piti\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl .Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt.\n### Odakle Ga Nabavljamo\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis.',
    },
    {
      id: '6',
      name: 'Čaj od Kamilice',
      picture: '../assets/camomile-tea.png',
      price: 500,
      text: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sunt nostrum quia labore facilis corporis illum voluptatum cupiditate eos neque temporibus!',
      desc: '## Čaj od Kamilice\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl. \n### Za Šta Je Dobar\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl .Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl.\n### Koliko Često Piti\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl .Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt.\n### Odakle Ga Nabavljamo\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis.',
    },
    {
      id: '7',
      name: 'Čaj od Hibiskusa',
      picture: '../assets/hibiscus-tea.png',
      price: 500,
      text: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sunt nostrum quia labore facilis corporis illum voluptatum cupiditate eos neque temporibus!',
      desc: '## Čaj od Hibiskusa\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl. \n### Za Šta Je Dobar\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl .Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl.\n### Koliko Često Piti\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl .Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt.\n### Odakle Ga Nabavljamo\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis.',
    },
    {
      id: '8',
      name: 'Čaj od Hibiskusa',
      picture: '../assets/hibiscus-tea.png',
      price: 500,
      text: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sunt nostrum quia labore facilis corporis illum voluptatum cupiditate eos neque temporibus!',
      desc: '## Čaj od Hibiskusa\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl. \n### Za Šta Je Dobar\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl .Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl.\n### Koliko Često Piti\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl .Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt.\n### Odakle Ga Nabavljamo\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis.',
    },
    {
      id: '9',
      name: 'Čaj od Hibiskusa',
      picture: '../assets/hibiscus-tea.png',
      price: 500,
      text: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sunt nostrum quia labore facilis corporis illum voluptatum cupiditate eos neque temporibus!',
      desc: '## Čaj od Hibiskusa\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl. \n### Za Šta Je Dobar\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl .Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl.\n### Koliko Često Piti\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl .Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt.\n### Odakle Ga Nabavljamo\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis.',
    },
    {
      id: '10',
      name: 'Čaj od Hibiskusa',
      picture: '../assets/hibiscus-tea.png',
      price: 500,
      text: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sunt nostrum quia labore facilis corporis illum voluptatum cupiditate eos neque temporibus!',
      desc: '## Čaj od Hibiskusa\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl. \n### Za Šta Je Dobar\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl .Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl.\n### Koliko Često Piti\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl .Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt.\n### Odakle Ga Nabavljamo\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis.',
    },
    {
      id: '11',
      name: 'Čaj od Hibiskusa',
      picture: '../assets/hibiscus-tea.png',
      price: 500,
      text: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sunt nostrum quia labore facilis corporis illum voluptatum cupiditate eos neque temporibus!',
      desc: '## Čaj od Hibiskusa\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl. \n### Za Šta Je Dobar\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl .Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl.\n### Koliko Često Piti\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt. Aliquam varius velit in lacus pulvinar, ut dignissim enim vestibulum. Nam sit amet elit massa. Aliquam ut diam tempor, facilisis leo sodales, facilisis nisl .Phasellus augue nisl, bibendum venenatis turpis a, condimentum pretium mauris. Nulla sollicitudin tempus lectus ac vulputate. Integer auctor eros vitae mauris gravida tincidunt.\n### Odakle Ga Nabavljamo\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet fermentum est, non luctus sapien. Cras eget enim ligula. Nam mattis, massa sed euismod semper, ipsum velit scelerisque justo, dignissim dapibus libero nulla nec lorem. Phasellus augue nisl, bibendum venenatis turpis.',
    },
  ];
  getProducts() {
    return this.productsArray;
  }
  getSingleProduct(id: string): ProductInterface {
    return this.productsArray.filter((prod) => prod.id === id)[0];
  }
}
